### ISSUE TITLE
Border box doesn't work

### ISSUE THREAD

**Issue by TriNguyen479** [TriNguyen479/type-those-grids#1]
@anna-pokhilenko
![image](https://user-images.githubusercontent.com/77295941/112864568-ead7e680-9085-11eb-8b45-d6f0a2a9825e.png)

**Comment by anna-pokhilenko** [comment]
Hello)
There are some suggestions:

1. Add img { width: 100%; } to your css.
2. I spotted that **in your header, you have a figure with an image**. I suggest you **put it in the main section**. You will have an **image called banner** and a **div with h2 and p** followed by all the figures. (Instead of the div create figures! It will make a little bit more sense semantically)
This way you will be able to spread the banner across three columns and assign each figure you have a column. It should look like that:
    `main { display: grid; 
    grid-template-columns: 1fr 1fr 1fr; 
    grid-template-areas: 
    "banner banner banner" 
    "col1 col2 col3"; }`
    **Please note that the grid should be put in the main section because we want to leave the header alone so it would span across the page and wouldn't intersect with our grid.**
    
3. When you are assigning the grid-area do not put the name in the quotation marks and don't forget to close the expression with a semi-column. For example:
` grid-area: header;`

    This should help with your layout!
